INSERT INTO PRODUCT(PRODUCT_ID, NAME) VALUES (1, 'XIAOMI EARPHONES');

INSERT INTO PRICE(PRICE_ID, PRODUCT_ID, AMOUNT, CURRENCY) VALUES (100, 1, 50.5, 'DOLLAR');
INSERT INTO PRICE(PRICE_ID, PRODUCT_ID, AMOUNT, CURRENCY) VALUES (101, 1, 50.5, 'EURO');