CREATE TABLE IF NOT EXISTS `shop`.`product` (
`PRODUCT_ID` BIGINT UNSIGNED NOT NULL COMMENT '',
`NAME` VARCHAR(100) NOT NULL COMMENT '',
PRIMARY KEY (`PRODUCT_ID`)  COMMENT '')ENGINE=InnoDB DEFAULT CHARSET=UTF8;


CREATE TABLE IF NOT EXISTS `shop`.`price` (
`PRICE_ID` BIGINT UNSIGNED NOT NULL COMMENT '',
`PRODUCT_ID` BIGINT UNSIGNED NOT NULL COMMENT '',
`AMOUNT` DECIMAL(10,2) NOT NULL COMMENT '',
`CURRENCY` ENUM('DOLLAR', 'EURO') NOT NULL COMMENT '',
PRIMARY KEY (`PRICE_ID`)  COMMENT '',
INDEX `PRICE_PRODUCT_FK_idx` (`PRODUCT_ID` ASC)  COMMENT '',
CONSTRAINT `PRICE_PRODUCT_FK`
    FOREIGN KEY (`PRODUCT_ID`)
        REFERENCES `shop`.`product` (`PRODUCT_ID`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)ENGINE=InnoDB DEFAULT CHARSET=UTF8;


CREATE TABLE IF NOT EXISTS `shop`.`sales` (
`SALE_ID` BINARY(16) NOT NULL COMMENT '',
`PRODUCT_ID` BIGINT UNSIGNED NOT NULL COMMENT '',
`USERNAME` VARCHAR(50) NOT NULL COMMENT '',
`OCCURRED_AT` DATETIME NOT NULL COMMENT '',
PRIMARY KEY (`SALE_ID`)  COMMENT '',
INDEX `SALES_PRODUCT_FK_idx` (`PRODUCT_ID` ASC)  COMMENT '',
CONSTRAINT `SALES_PRODUCT_FK`
    FOREIGN KEY (`PRODUCT_ID`)
        REFERENCES `shop`.`product` (`PRODUCT_ID`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)ENGINE=InnoDB DEFAULT CHARSET=UTF8;