INSERT INTO `shop`.`product`(PRODUCT_ID, NAME) VALUES (1, 'XIAOMI EARPHONES');

INSERT INTO `shop`.`price`(PRICE_ID, PRODUCT_ID, AMOUNT, CURRENCY) VALUES (100, 1, 50.50, 'DOLLAR');
INSERT INTO `shop`.`price`(PRICE_ID, PRODUCT_ID, AMOUNT, CURRENCY) VALUES (101, 1, 50.50, 'EURO');